### ISSUE TITLE
README uses deprecated `command`

### ISSUE THREAD

**Issue by rondonjon** [drew-y/cliffy#14]
The example in the README uses the deprecated command

```
  .command("run", {
```

and is missing a comma:

```
            }
            from: {
```

**Comment by drew-y** [comment]
Fixed in 7bb7801. Thanks!

**Comment by KaKi87** [comment]
Hello, it's still the case, there currently are 3 occurences of `.command` in README, thanks.

**Comment by drew-y** [comment]
@KaKi87 Thanks for letting me know. Fixed in 8cd0980bb2cb8619a335708990c23c69bd1a45ba.
