### ISSUE TITLE
Commands take more arguments than supported

### ISSUE THREAD

**Issue by rondonjon** [drew-y/cliffy#15]
I just ran the example snippet and was surprised that this is accepted as input:

```
-->run foo bar
```

The command supports only one argument; if more are provided, I would expect that the CLI yields an error message that reminds the user of the correct syntax, but the CLI seems to ignore the superflous input silently and outputs this:

```
I ran to foo
-->
```

**Comment by drew-y** [comment]
Fixed in v2.4.1. Thanks!
