### ISSUE TITLE
console logs from outside of the CLI function are being ignored

### ISSUE THREAD

**Issue by prajjwaldimri** [drew-y/cliffy#17]
Hi, Thanks for this great library.

I was implementing this in my project and noticed that only console.log() from inside the CLI function is displayed on the prompt. Is there any way to show logs from other files in the project?

**Comment by prajjwaldimri** [comment]
Ok, the logs not being displayed was some issue with the `discovery-swarm` module.
Now the logs are being shown, however they are being displayed on the prompt e.g.

`> logs from outside the cli function will be shown here`

instead of

```
logs shown here
>
```

Is there any way to mitigate this issue?

**Comment by drew-y** [comment]
That is an inherent limitation of console.log unfortunately. There is no way for the prompt to know that something is being logged external to the command function. Thankfully it's just a minor visual inconvenience. You can hit enter a few times to bring the prompt back down.

That being said there is technically a way to get the behavior your looking for. The Cliffy constructor signature looks like this:
```typescript
class CLI {
    constructor(opts: {
        input?: NodeJS.ReadableStream,
        output?: NodeJS.WritableStream
    } = {})
}
```

Which means you can actually output to any arbitrary `WritableStream`. This defaults to `stdout`, but it could be anything. A file, a websocket, etc. You could even get really clever and make your own logging library that gives normal logs and the prompt their own space. It's really up to how much work your willing to put into it.

A quick and dirty idea would be to redirect the input and output to a different process using something like a net.Socket. Under this scenario the CLI would be a server that another process connects to. That would mean you'd enter your commands in a separate terminal than the one that logs to the main terminal.

Hope these ideas help!

**Comment by prajjwaldimri** [comment]
Thanks! :)
