### ISSUE TITLE
[Request] Command Aliases

### ISSUE THREAD

**Issue by NBTX** [drew-y/cliffy#7]
I may do a PR for this if I have time - I imagine this should be relatively simple?
Basically, my feature request just an array of aliases - set as a property on addCommand. Then, you can use these to execute the command as well as the normal trigger.

(The aliases wouldn't have to show up in `help`)

**Comment by drew-y** [comment]
That should be pretty straight forward. You're welcome to submit a PR but I will probably be able to get to it this week as well.

**Comment by drew-y** [comment]
Done in v2.1.0 (commit d0bc0c2b2f85).
